version: 2
jobs:
    build:
        docker:
            - image: level12/python-test-multi:latest

        steps:
            - checkout

            - run:
                name: folder listing for debugging
                command: ls -al

            - run:
                name: install testing helpers needed at OS level
                command: >
                    python3.6 -m pip install tox pipenv

            - run:
                name: version checks
                command: |
                    python3.6 --version
                    tox --version
                    pipenv --version

            - run:
                name: run tox
                command: tox

            - store_test_results:
                path: .ci/test-reports/

            - run:
                name: push code coverage
                command: bash <(curl -s https://codecov.io/bash) -X coveragepy -t 4c3bde62-6dd7-439b-b741-d7b7d806a1a2
